# openapi2-run.yaml
swagger: '2.0'
info:
  title: gateway-grpc optional-string
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://gateway-grpc-ttzemat6za-uk.a.run.app
paths:
  /Play/CreateGame:
    post:
      operationId: Play_CreateGame
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/CreateGameResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateGameRequest'
      tags:
        - Play
definitions:
  CreateGameRequest:
    type: object
  CreateGameResponse:
    type: object
    properties:
      createdGame:
        $ref: '#/definitions/Game'
  Game:
    type: object
    properties:
      id:
        type: string
      owner:
        type: string
      participants:
        type: array
        items:
          type: string
      status:
        $ref: '#/definitions/GameStatus'
  GameStatus:
    type: string
    enum:
      - LISTED
      - PENDING
      - CONFIRMED
      - IN_PROGRESS
      - COMPLETED
      - CANCELLED
    default: LISTED
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
