name: Athlas Gateway - Deploy

on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string
    secrets:
      PROJECT_ID:
        required: true
      GCP_SA_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    steps:
      # Build and deploy to dev
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
            project_id: ${{ secrets.PROJECT_ID }}

      - name: Build and push Docker image
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          gcloud auth configure-docker
          docker build --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" -t gcr.io/${{ secrets.PROJECT_ID }}/gateway:${{ inputs.ENV_NAME }}
          docker push gcr.io/${{ secrets.PROJECT_ID }}/gateway-${{ inputs.ENV_NAME }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy gateway-${{ inputs.ENV_NAME }} \
            --platform managed \
            --region us-central1 \
            --image gcr.io/${{ secrets.PROJECT_ID }}/gateway:${{ inputs.ENV_NAME }} \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars GRPC_GO_LOG_SEVERITY_LEVEL=INFO
