name: Athlas Gateway - Pull Request

run-name: Pull Request | test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/athlas-app/*

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v3
      - name: Authenticate with GitHub
        env:
          PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "machine github.com login $PAT_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: go build
      - run: go test
