name: Athlas Gateway - CI Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - name: DEV
            PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
            GCP_SA_KEY: ${{ secrets.DEV_GCP_SA_KEY }}
          - name: PROD
            PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
            GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
    environment: production
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      # Change version number
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      # Build and deploy to dev
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
            project_id: ${{ matrix.env.PROJECT_ID }}

      - name: Build and push Docker image
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GCP_PROJECT_ID: ${{ matrix.env.PROJECT_ID }}
        run: |
          gcloud auth configure-docker
          docker build --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" -t gcr.io/$GCP_PROJECT_ID/gateway:${{ matrix.env.name }} .
          docker push gcr.io/$GCP_PROJECT_ID/gateway-${{ matrix.env.name }}

      - name: Deploy to Google Cloud Run
        env:
          GCP_PROJECT_ID: ${{ matrix.env.PROJECT_ID }}
        run: |
          gcloud run deploy gateway-${{ matrix.env.name }} \
            --platform managed \
            --region us-central1 \
            --image gcr.io/$GCP_PROJECT_ID/gateway:${{ matrix.env.name }} \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars GRPC_GO_LOG_SEVERITY_LEVEL=INFO
