name: Athlas Gateway - CI Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: DEV
            project_id: DEV_PROJECT_ID
            gcp_sa_key: DEV_GCP_SA_KEY
          - environment: PROD
            project_id: PROD_PROJECT_ID
            gcp_sa_key: PROD_GCP_SA_KEY
    env:
      ENV_NAME: ${{ matrix.environment }}
      PROJECT_ID: ${{ secrets[matrix.project_id] }}
      GCP_SA_KEY: ${{ secrets[matrix.gcp_sa_key] }}
    environment: ${{ matrix.env.name }}
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      # Change version number
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      ENV: DEV
    secrets:
      PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.DEV_GCP_SA_KEY }}
  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      ENV: PROD
    secrets:
      PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
